#can be others, now we hard code the kubernetes in the source code,future fix up it
clusterName: kubernetes
#loadbalancer address,for others access apiserver
advertiseAddress: 10.0.0.1
#master can be 3 or 5,suggest is 3
masters:
  - publicIP: 43.3.123.23
    privateIP: 192.168.0.1
    user: root
    password: password
nodes:
  - publicIP: 49.34.123.5
    privateIP: 192.168.0.1
    user: root
    password: password