// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

package master

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type MasterConfig struct {
	PublicIP             string   `protobuf:"bytes,1,opt,name=publicIP,proto3" json:"publicIP,omitempty"`
	PrivateIP            string   `protobuf:"bytes,2,opt,name=privateIP,proto3" json:"privateIP,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterConfig) Reset()         { *m = MasterConfig{} }
func (m *MasterConfig) String() string { return proto.CompactTextString(m) }
func (*MasterConfig) ProtoMessage()    {}
func (*MasterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

func (m *MasterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterConfig.Unmarshal(m, b)
}
func (m *MasterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterConfig.Marshal(b, m, deterministic)
}
func (m *MasterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterConfig.Merge(m, src)
}
func (m *MasterConfig) XXX_Size() int {
	return xxx_messageInfo_MasterConfig.Size(m)
}
func (m *MasterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MasterConfig proto.InternalMessageInfo

func (m *MasterConfig) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *MasterConfig) GetPrivateIP() string {
	if m != nil {
		return m.PrivateIP
	}
	return ""
}

func (m *MasterConfig) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *MasterConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// The response message containing the greetings
type JoinResponse struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *JoinResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MasterConfig)(nil), "master.MasterConfig")
	proto.RegisterType((*JoinResponse)(nil), "master.JoinResponse")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x31, 0x6f, 0x83, 0x30,
	0x10, 0x85, 0x4b, 0x4b, 0x69, 0x39, 0x31, 0x9d, 0x18, 0x2c, 0xd4, 0xa1, 0x62, 0xea, 0xc4, 0xd0,
	0x76, 0x66, 0xe9, 0x44, 0xa5, 0x4a, 0x88, 0x7f, 0x60, 0x9a, 0x0b, 0xb2, 0x14, 0xb0, 0xe5, 0x33,
	0x49, 0x7e, 0x7e, 0x14, 0xe3, 0x10, 0xb6, 0xfb, 0xde, 0x93, 0xde, 0xf3, 0x33, 0x64, 0xa3, 0x64,
	0x47, 0xb6, 0x32, 0x56, 0x3b, 0x8d, 0xc9, 0x42, 0xe5, 0x19, 0xb2, 0x3f, 0x7f, 0xfd, 0xe8, 0x69,
	0xaf, 0x06, 0x2c, 0xe0, 0xd5, 0xcc, 0xfd, 0x41, 0xfd, 0x37, 0xad, 0x88, 0xde, 0xa3, 0x8f, 0xb4,
	0x5b, 0x19, 0xdf, 0x20, 0x35, 0x56, 0x1d, 0xa5, 0xa3, 0xa6, 0x15, 0x8f, 0xde, 0xbc, 0x0b, 0x88,
	0x10, 0xcf, 0x4c, 0x56, 0x3c, 0x79, 0xc3, 0xdf, 0x3e, 0x4d, 0x32, 0x9f, 0xb4, 0xdd, 0x89, 0x38,
	0xa4, 0x05, 0x2e, 0x6b, 0xc8, 0x7e, 0xb5, 0x9a, 0x3a, 0x62, 0xa3, 0x27, 0x26, 0xcc, 0xe1, 0x99,
	0x9d, 0x74, 0x14, 0x6a, 0x17, 0x40, 0x01, 0x2f, 0x23, 0x31, 0xcb, 0x81, 0x42, 0xe3, 0x0d, 0x3f,
	0x6b, 0x48, 0x96, 0x97, 0xe3, 0x37, 0xc4, 0xd7, 0x24, 0xcc, 0xab, 0x30, 0x71, 0xbb, 0xa8, 0x58,
	0xd5, 0x6d, 0x5b, 0xf9, 0xd0, 0x27, 0xfe, 0x23, 0xbe, 0x2e, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80,
	0xac, 0x61, 0x56, 0x18, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	// Sends a greeting
	Join(ctx context.Context, in *MasterConfig, opts ...grpc.CallOption) (*JoinResponse, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Join(ctx context.Context, in *MasterConfig, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/master.Master/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	// Sends a greeting
	Join(context.Context, *MasterConfig) (*JoinResponse, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/master.Master/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Join(ctx, req.(*MasterConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "master.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Master_Join_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}
