apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --initial-cluster=node1=http://192.168.1.2:2380,node2=http://192.168.1.3:2380,node0=http://192.168.50.173:2380
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --data-dir=/var/lib/etcd
    - --peer-client-cert-auth=true
    - --client-cert-auth=true
    - --advertise-client-urls=http://192.168.50.173:2379
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --listen-peer-urls=http://192.168.50.173:2380
    - --initial-advertise-peer-urls=http://192.168.50.173:2380
    - --listen-client-urls=http://192.168.50.173:2379,http://127.0.0.1:2379
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --initial-cluster-state=new
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --initial-cluster-token=token
    - --name=node0
    image: k8s.gcr.io/etcd:3.3.10
    imagePullPolicy: IfNotPresent
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: data
    - mountPath: /etc/kubernetes/pki/etcd
      name: certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/etcd
      type: Directory
    name: data
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: Directory
    name: certs
status: {}
