// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ServerConfig struct {
	PublicIP             string   `protobuf:"bytes,1,opt,name=publicIP,proto3" json:"publicIP,omitempty"`
	PrivateIP            string   `protobuf:"bytes,2,opt,name=privateIP,proto3" json:"privateIP,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ClusterName          string   `protobuf:"bytes,5,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConfig) Reset()         { *m = ServerConfig{} }
func (m *ServerConfig) String() string { return proto.CompactTextString(m) }
func (*ServerConfig) ProtoMessage()    {}
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}

func (m *ServerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfig.Unmarshal(m, b)
}
func (m *ServerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfig.Marshal(b, m, deterministic)
}
func (m *ServerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfig.Merge(m, src)
}
func (m *ServerConfig) XXX_Size() int {
	return xxx_messageInfo_ServerConfig.Size(m)
}
func (m *ServerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfig proto.InternalMessageInfo

func (m *ServerConfig) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *ServerConfig) GetPrivateIP() string {
	if m != nil {
		return m.PrivateIP
	}
	return ""
}

func (m *ServerConfig) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ServerConfig) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ServerConfig) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type ClusterConfig struct {
	ClusterName          string          `protobuf:"bytes,1,opt,name=clusterName,proto3" json:"clusterName,omitempty"`
	AdvertiseAddress     string          `protobuf:"bytes,2,opt,name=advertiseAddress,proto3" json:"advertiseAddress,omitempty"`
	PublicIP             string          `protobuf:"bytes,3,opt,name=publicIP,proto3" json:"publicIP,omitempty"`
	DownloadBinSite      string          `protobuf:"bytes,4,opt,name=downloadBinSite,proto3" json:"downloadBinSite,omitempty"`
	Masters              []*ServerConfig `protobuf:"bytes,5,rep,name=masters,proto3" json:"masters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClusterConfig) Reset()         { *m = ClusterConfig{} }
func (m *ClusterConfig) String() string { return proto.CompactTextString(m) }
func (*ClusterConfig) ProtoMessage()    {}
func (*ClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}

func (m *ClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterConfig.Unmarshal(m, b)
}
func (m *ClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterConfig.Marshal(b, m, deterministic)
}
func (m *ClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterConfig.Merge(m, src)
}
func (m *ClusterConfig) XXX_Size() int {
	return xxx_messageInfo_ClusterConfig.Size(m)
}
func (m *ClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterConfig proto.InternalMessageInfo

func (m *ClusterConfig) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ClusterConfig) GetAdvertiseAddress() string {
	if m != nil {
		return m.AdvertiseAddress
	}
	return ""
}

func (m *ClusterConfig) GetPublicIP() string {
	if m != nil {
		return m.PublicIP
	}
	return ""
}

func (m *ClusterConfig) GetDownloadBinSite() string {
	if m != nil {
		return m.DownloadBinSite
	}
	return ""
}

func (m *ClusterConfig) GetMasters() []*ServerConfig {
	if m != nil {
		return m.Masters
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "proto.Response")
	proto.RegisterType((*ServerConfig)(nil), "proto.ServerConfig")
	proto.RegisterType((*ClusterConfig)(nil), "proto.ClusterConfig")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0xbe, 0xbd, 0x94, 0xbf, 0xc3, 0xbd, 0xc1, 0x1c, 0x5d, 0x4c, 0x88, 0x0b, 0xd2, 0x15, 0x31,
	0x11, 0xb5, 0x6e, 0xdc, 0x2a, 0x6e, 0x30, 0x91, 0x10, 0x78, 0x82, 0x81, 0x39, 0xe2, 0x98, 0xb6,
	0xd3, 0xcc, 0x0c, 0xf0, 0x2e, 0x3e, 0x96, 0x4f, 0x64, 0x3a, 0x0c, 0xc8, 0xdf, 0x82, 0x8d, 0x9b,
	0x76, 0xce, 0xd7, 0x7e, 0x7f, 0x3d, 0x85, 0x46, 0xae, 0x95, 0x55, 0x5d, 0x77, 0xc5, 0xb2, 0xbb,
	0x45, 0x0f, 0x50, 0x1b, 0x91, 0xc9, 0x55, 0x66, 0x08, 0x11, 0xc2, 0xa9, 0x12, 0xc4, 0x82, 0x76,
	0xd0, 0xa9, 0x8f, 0xdc, 0x19, 0x19, 0x54, 0x53, 0x32, 0x86, 0xcf, 0x88, 0xfd, 0x75, 0xf0, 0x7a,
	0x8c, 0x3e, 0x03, 0xf8, 0x37, 0x26, 0xbd, 0x20, 0xdd, 0x53, 0xd9, 0x9b, 0x9c, 0x61, 0x0b, 0x6a,
	0xf9, 0x7c, 0x92, 0xc8, 0x69, 0x7f, 0xe8, 0x25, 0x36, 0x33, 0x5e, 0x42, 0x3d, 0xd7, 0x72, 0xc1,
	0x2d, 0xf5, 0x87, 0x5e, 0xe8, 0x07, 0x28, 0x8c, 0xe7, 0x86, 0x34, 0x2b, 0xad, 0x8c, 0x8b, 0xb3,
	0x53, 0xe3, 0xc6, 0x2c, 0x95, 0x16, 0x2c, 0xf4, 0x6a, 0x7e, 0xc6, 0x36, 0x34, 0xa6, 0xc9, 0xdc,
	0x58, 0xd2, 0x03, 0x9e, 0x12, 0x2b, 0xbb, 0xc7, 0xdb, 0x50, 0xf4, 0x15, 0xc0, 0xff, 0xde, 0x6a,
	0xf6, 0xe9, 0xf6, 0x38, 0xc1, 0x01, 0x07, 0xaf, 0xe0, 0x8c, 0x8b, 0x05, 0x69, 0x2b, 0x0d, 0x3d,
	0x0a, 0xa1, 0xc9, 0x18, 0x1f, 0xf5, 0x00, 0xdf, 0xe9, 0x5a, 0xda, 0xeb, 0xda, 0x81, 0xa6, 0x50,
	0xcb, 0x2c, 0x51, 0x5c, 0x3c, 0xc9, 0x6c, 0x2c, 0x2d, 0xf9, 0x02, 0xfb, 0x30, 0x5e, 0x43, 0x35,
	0xe5, 0x85, 0xbf, 0x61, 0xe5, 0x76, 0xa9, 0xd3, 0x88, 0xcf, 0x57, 0xcb, 0xe9, 0x6e, 0x7f, 0xd7,
	0xd1, 0xfa, 0x9d, 0x38, 0x85, 0xaa, 0xcf, 0x8b, 0x37, 0x10, 0xf6, 0x33, 0x69, 0xf1, 0xc2, 0x13,
	0x76, 0xba, 0xb6, 0x9a, 0x1e, 0x5d, 0x6f, 0x36, 0xfa, 0x83, 0x77, 0x50, 0x79, 0xa6, 0x84, 0x2c,
	0x9d, 0x4c, 0x89, 0x3f, 0xa0, 0xf2, 0xea, 0x9c, 0xb1, 0x0b, 0xe1, 0x8b, 0x92, 0x19, 0x1e, 0x8b,
	0x77, 0xcc, 0xec, 0x76, 0x63, 0x76, 0x22, 0x23, 0x7e, 0x87, 0x70, 0x50, 0xfc, 0x6e, 0xbf, 0xee,
	0x34, 0xa9, 0x38, 0xe4, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x25, 0x21, 0x09, 0x0d, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	Init(ctx context.Context, in *ClusterConfig, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *ClusterConfig, opts ...grpc.CallOption) (*Response, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) Init(ctx context.Context, in *ClusterConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.cluster/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterClient) Delete(ctx context.Context, in *ClusterConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.cluster/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	Init(context.Context, *ClusterConfig) (*Response, error)
	Delete(context.Context, *ClusterConfig) (*Response, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cluster/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Init(ctx, req.(*ClusterConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cluster_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.cluster/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).Delete(ctx, req.(*ClusterConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Cluster_Init_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Cluster_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	Join(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Join(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Master/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) Delete(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Master/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	Join(context.Context, *ServerConfig) (*Response, error)
	Delete(context.Context, *ServerConfig) (*Response, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Master/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Join(ctx, req.(*ServerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Master/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Delete(ctx, req.(*ServerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Master_Join_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Master_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Join(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Join(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Node/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) Delete(ctx context.Context, in *ServerConfig, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/proto.Node/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Join(context.Context, *ServerConfig) (*Response, error)
	Delete(context.Context, *ServerConfig) (*Response, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Node/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Join(ctx, req.(*ServerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Node/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Delete(ctx, req.(*ServerConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Node_Join_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Node_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
